# Documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: FinanceUnderControl

options:
  bundleIdPrefix: sebastian-staszczyk
  groupSortPosition: bottom
  platform: iOS
  deploymentTarget:
    iOS: 15.0

packages:
 Firebase:
   url: https://github.com/firebase/firebase-ios-sdk
   from: 9.0.0

localPackages:
  - ./Packages/Domain
  - ./Packages/FinanceCoreData
  - ./Packages/Shared
  - ~/Developer/ss_libraries/SSValidation
  - ~/Developer/ss_libraries/SSUtils

targets:
  FinanceUnderControl:
    scheme:
      testTargets:
        - FinanceUnderControl
        - name: FinanceUnderControl
          parallelizable: true
      gatherCoverageData: true
    templates:
      - FinanceUnderControl
    dependencies:
      - package: Domain
      - package: FinanceCoreData
      - package: Shared
      - package: SSUtils
      - package: SSValidation
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore

  FinanceUnderControlTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FinanceUnderControlTests
    scheme:
      testTargets:
        - FinanceUnderControlTests
      gatherCoverageData: true
    dependencies:
      - target: FinanceUnderControl

targetTemplates:
    FinanceUnderControl:
      platform: iOS
      type: application
      sources: [FinanceUnderControl]
